### ISSUE TITLE
Reg. Dynamics and Control sessions

### ISSUE THREAD

**Issue by suraj2596** [RoboticsIIITH/summer-sessions-2020#27]
Dear all,

I hope everyone is doing well in these tough times. 

By now you have learnt various concepts from your seniors. From Monday, we'll be presenting you concepts of drone dynamics and control theory. 

These mathematical concepts will be discussed in the next 4 days, starting from Monday.

15th: quadrotor drones
16th: linear control
17th (9.30 am to 11 am): non-linear control - Prof Spandan Roy 
18th: fixed-wing drones - Prof Harikumar Kandath

Note: Although timings for classes are usually in the afternoon, the class on 15th will be at 11 am for roughly an hour. In case you are unable to attend in the morning, the class will be recorded and you can mail me for doubts if any. Inconvenience is regretted.

Looking forward to meet you all!
Cheers!

Regards,
Suraj

**Comment by Shubodh** [comment]
Prof Spandan Roy will take the class from 9.30 am to 11 am morning on Wednesday (17th). 

Prof Harikumar Kandath will take the class from 3.00 to 4.30 PM on Thursday (18th).

This is the first time a summer school session is being taken by professors, so please make good use of it. Professors are looking forward to high attendance and participation.
